-- Names batch 3: Combi/Galileo ovens, Cookers, Gas hobs.
BEGIN;
UPDATE products p SET name_en = m.en, name = m.ru, name_hy = m.hy
FROM (VALUES
($q$Combi Microwave Oven | Galileo technology 45 cm Classica aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Classica$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Classica էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 45 cm Dolce Stil Novo aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Dolce Stil Novo$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 45 cm Linea aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Linea$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Linea էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 45 cm Musa aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Musa$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Musa էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 45 cm Selezione aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Selezione$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Selezione էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 45 cm Victoria aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 45 см, линия Victoria$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 45 սմ, Victoria էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 60 cm Classica aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 60 см, линия Classica$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 60 սմ, Classica էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 60 cm Dolce Stil Novo aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 60 см, линия Dolce Stil Novo$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 60 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 60 cm Linea aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 60 см, линия Linea$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 60 սմ, Linea էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 60 cm Musa aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 60 см, линия Musa$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 60 սմ, Musa էսթետիկա$q$),
($q$Combi Microwave Oven | Galileo technology 60 cm Selezione aesthetic line$q$,$q$Комбинированная микроволновая печь | Galileo technology 60 см, линия Selezione$q$,$q$Համակցված միկրոալիքային վառարան | Galileo technology 60 սմ, Selezione էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 45 cm Classica aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 45 см, линия Classica$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 45 սմ, Classica էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 45 cm Dolce Stil Novo aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 45 см, линия Dolce Stil Novo$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 45 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 45 cm Linea aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 45 см, линия Linea$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 45 սմ, Linea էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 45 cm Musa aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 45 см, линия Musa$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 45 սմ, Musa էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Classica aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Classica$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Classica էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Dolce Stil Novo aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Dolce Stil Novo$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Linea aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Linea$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Linea էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Musa aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Musa$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Musa էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Selezione aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Selezione$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Selezione էսթետիկա$q$),
($q$Combi Steam Oven | Galileo technology 60 cm Victoria aesthetic line$q$,$q$Комбинированный пароварочный шкаф | Galileo technology 60 см, линия Victoria$q$,$q$Համակցված գոլորշու ջեռոց | Galileo technology 60 սմ, Victoria էսթետիկա$q$),
($q$Connecting Strip Accessory for: Hobs$q$,$q$Соединительная планка, аксессуар для: варочные панели$q$,$q$Միացման հատված, պարագա՝ կերակրասալերի համար$q$),
($q$Containers set Accessory for: Drawers$q$,$q$Набор контейнеров, аксессуар для: ящики$q$,$q$Տարաների հավաքածու, պարագա՝ դարակների համար$q$),
($q$Cooker with Ceramic Hob 90x60 cm Classica Aesthetic$q$,$q$Плита с керамической варочной панелью 90x60 см, эстетика Classica$q$,$q$Սալօջախ կերամիկական մակերեսով 90x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Gas Hob 100x60 cm Classica Aesthetic$q$,$q$Плита с газовой варочной панелью 100x60 см, эстетика Classica$q$,$q$Սալօջախ գազային մակերեսով 100x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Gas Hob 100x60 cm Victoria Aesthetic$q$,$q$Плита с газовой варочной панелью 100x60 см, эстетика Victoria$q$,$q$Սալօջախ գազային մակերեսով 100x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Gas Hob 110x60 cm Classica Aesthetic$q$,$q$Плита с газовой варочной панелью 110x60 см, эстетика Classica$q$,$q$Սալօջախ գազային մակերեսով 110x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Gas Hob 110x60 cm Victoria Aesthetic$q$,$q$Плита с газовой варочной панелью 110x60 см, эстетика Victoria$q$,$q$Սալօջախ գազային մակերեսով 110x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Gas Hob 60x60 cm Classica Aesthetic$q$,$q$Плита с газовой варочной панелью 60x60 см, эстетика Classica$q$,$q$Սալօջախ գազային մակերեսով 60x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Gas Hob 60x60 cm Mista Aesthetic$q$,$q$Плита с газовой варочной панелью 60x60 см, эстетика Mista$q$,$q$Սալօջախ գազային մակերեսով 60x60 սմ, Mista էսթետիկա$q$),
($q$Cooker with Gas Hob 60x60 cm Victoria Aesthetic$q$,$q$Плита с газовой варочной панелью 60x60 см, эстетика Victoria$q$,$q$Սալօջախ գազային մակերեսով 60x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Gas Hob 90x60 cm Classica Aesthetic$q$,$q$Плита с газовой варочной панелью 90x60 см, эстетика Classica$q$,$q$Սալօջախ գազային մակերեսով 90x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Gas Hob 90x60 cm Victoria Aesthetic$q$,$q$Плита с газовой варочной панелью 90x60 см, эстетика Victoria$q$,$q$Սալօջախ գազային մակերեսով 90x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Gas Hob Divina Cucina, 90x60 cm Victoria Aesthetic$q$,$q$Плита с газовой варочной панелью Divina Cucina, 90x60 см, эстетика Victoria$q$,$q$Սալօջախ գազային մակերեսով Divina Cucina, 90x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Induction Hob 100x60 cm Victoria Aesthetic$q$,$q$Плита с индукционной варочной панелью 100x60 см, эстетика Victoria$q$,$q$Սալօջախ ինդուկցիոն մակերեսով 100x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Induction Hob 110x60 cm Victoria Aesthetic$q$,$q$Плита с индукционной варочной панелью 110x60 см, эстетика Victoria$q$,$q$Սալօջախ ինդուկցիոն մակերեսով 110x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Induction Hob 60x60 cm Victoria Aesthetic$q$,$q$Плита с индукционной варочной панелью 60x60 см, эстетика Victoria$q$,$q$Սալօջախ ինդուկցիոն մակերեսով 60x60 սմ, Victoria էսթետիկա$q$),
($q$Cooker with Induction Hob 90x60 cm Classica Aesthetic$q$,$q$Плита с индукционной варочной панелью 90x60 см, эстетика Classica$q$,$q$Սալօջախ ինդուկցիոն մակերեսով 90x60 սմ, Classica էսթետիկա$q$),
($q$Cooker with Induction Hob 90x60 cm Victoria Aesthetic$q$,$q$Плита с индукционной варочной панелью 90x60 см, эстетика Victoria$q$,$q$Սալօջախ ինդուկցիոն մակերեսով 90x60 սմ, Victoria էսթետիկա$q$),
($q$Gas Hob 30 cm Classica aesthetic$q$,$q$Газовая варочная панель 30 см, эстетика Classica$q$,$q$Գազօջախ 30 սմ, Classica էսթետիկա$q$),
($q$Gas Hob 30 cm Contemporanea aesthetic$q$,$q$Газовая варочная панель 30 см, эстетика Contemporanea$q$,$q$Գազօջախ 30 սմ, Contemporanea էսթետիկա$q$),
($q$Gas Hob 60 cm Classica aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Classica$q$,$q$Գազօջախ 60 սմ, Classica էսթետիկա$q$),
($q$Gas Hob 60 cm Coloniale aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Coloniale$q$,$q$Գազօջախ 60 սմ, Coloniale էսթետիկա$q$),
($q$Gas Hob 60 cm Contemporanea aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Contemporanea$q$,$q$Գազօջախ 60 սմ, Contemporanea էսթետիկա$q$),
($q$Gas Hob 60 cm Cortina aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Cortina$q$,$q$Գազօջախ 60 սմ, Cortina էսթետիկա$q$),
($q$Gas Hob 60 cm Dolce Stil Novo aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Dolce Stil Novo$q$,$q$Գազօջախ 60 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Gas Hob 60 cm Linea aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Linea$q$,$q$Գազօջախ 60 սմ, Linea էսթետիկա$q$),
($q$Gas Hob 60 cm Selezione aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Selezione$q$,$q$Գազօջախ 60 սմ, Selezione էսթետիկա$q$),
($q$Gas Hob 60 cm Victoria aesthetic$q$,$q$Газовая варочная панель 60 см, эстетика Victoria$q$,$q$Գազօջախ 60 սմ, Victoria էսթետիկա$q$),
($q$Gas Hob 70/75 cm Classica aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Classica$q$,$q$Գազօջախ 70/75 սմ, Classica էսթետիկա$q$),
($q$Gas Hob 70/75 cm Coloniale aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Coloniale$q$,$q$Գազօջախ 70/75 սմ, Coloniale էսթետիկա$q$),
($q$Gas Hob 70/75 cm Contemporanea aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Contemporanea$q$,$q$Գազօջախ 70/75 սմ, Contemporanea էսթետիկա$q$),
($q$Gas Hob 70/75 cm Cortina aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Cortina$q$,$q$Գազօջախ 70/75 սմ, Cortina էսթետիկա$q$),
($q$Gas Hob 70/75 cm Selezione aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Selezione$q$,$q$Գազօջախ 70/75 սմ, Selezione էսթետիկա$q$),
($q$Gas Hob 70/75 cm Victoria aesthetic$q$,$q$Газовая варочная панель 70/75 см, эстетика Victoria$q$,$q$Գազօջախ 70/75 սմ, Victoria էսթետիկա$q$),
($q$Gas Hob 90 cm Classica aesthetic$q$,$q$Газовая варочная панель 90 см, эстетика Classica$q$,$q$Գազօջախ 90 սմ, Classica էսթետիկա$q$),
($q$Gas Hob 90 cm Coloniale aesthetic$q$,$q$Газовая варочная панель 90 см, эстетика Coloniale$q$,$q$Գազօջախ 90 սմ, Coloniale էսթետիկա$q$),
($q$Gas Hob 90 cm Contemporanea aesthetic$q$,$q$Газовая варочная панель 90 см, эстетика Contemporanea$q$,$q$Գազօջախ 90 սմ, Contemporanea էսթետիկա$q$),
($q$Gas Hob 90 cm Dolce Stil Novo aesthetic$q$,$q$Газовая варочная панель 90 см, эстетика Dolce Stil Novo$q$,$q$Գազօջախ 90 սմ, Dolce Stil Novo էսթետիկա$q$)
) AS m(en, ru, hy)
WHERE p.name_en IS NULL AND p.name = m.en;
COMMIT;
