-- Names batch 1. Match English source name; copy EN -> name_en, set RU -> name, HY -> name_hy.
BEGIN;
UPDATE products p SET name_en = m.en, name = m.ru, name_hy = m.hy
FROM (VALUES
($q$2 extra-wide slots Toaster Black 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, черный, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, սև, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Cream 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, кремовый, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, կրեմագույն, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Pastel blue 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, пастельный голубой, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, պաստել երկնագույն, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Pastel green 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, пастельный зеленый, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, պաստել կանաչ, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Pink 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, розовый, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, վարդագույն, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Red 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, красный, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, կարմիր, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster Steel 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, сталь, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, պողպատ, 50's Style էսթետիկա$q$),
($q$2 extra-wide slots Toaster White 50's Style Aesthetic$q$,$q$Тостер с 2 широкими слотами, белый, эстетика 50's Style$q$,$q$Տոստեր 2 լայն բացվածքով, սպիտակ, 50's Style էսթետիկա$q$),
($q$2-Piece sandwich racks Accessory for: Toaster TSSR01$q$,$q$Решётки для сэндвичей, 2 шт., аксессуар для: тостер TSSR01$q$,$q$Սենդվիչի վանդակաճաղեր, 2 հատ, պարագա՝ տոստեր TSSR01-ի համար$q$),
($q$2-Piece sandwich racks Accessory for: Toaster TSSR02$q$,$q$Решётки для сэндвичей, 2 шт., аксессуар для: тостер TSSR02$q$,$q$Սենդվիչի վանդակաճաղեր, 2 հատ, պարագա՝ տոստեր TSSR02-ի համար$q$),
($q$2-Slice Toaster Sicily is my love 50's Style aesthetic$q$,$q$Тостер на 2 ломтика Sicily is my love, эстетика 50's Style$q$,$q$Տոստեր 2 կտորի Sicily is my love, 50's Style էսթետիկա$q$),
($q$4 accessories set, Black version, Beaker, Chopper, Whisk, Masher Accessory for: Hand Blenders HBAC11BL$q$,$q$Набор из 4 аксессуаров, черный, мерный стакан, измельчитель, венчик, толкушка, аксессуар для: погружные блендеры HBAC11BL$q$,$q$4 պարագայի հավաքածու, սև, չափաբաժակ, մանրացուցիչ, հարիչ, տրորիչ, պարագա՝ ձեռքի բլենդերներ HBAC11BL-ի համար$q$),
($q$4 accessories set, Cream version, Beaker, Chopper, Whisk, Masher Accessory for: Hand Blenders HBAC11CR$q$,$q$Набор из 4 аксессуаров, кремовый, мерный стакан, измельчитель, венчик, толкушка, аксессуар для: погружные блендеры HBAC11CR$q$,$q$4 պարագայի հավաքածու, կրեմագույն, չափաբաժակ, մանրացուցիչ, հարիչ, տրորիչ, պարագա՝ ձեռքի բլենդերներ HBAC11CR-ի համար$q$),
($q$4 accessories set, Pastel blue version, Beaker, Chopper, Whisk, Masher Accessory for: Hand Blenders HBAC11PB$q$,$q$Набор из 4 аксессуаров, пастельный голубой, мерный стакан, измельчитель, венчик, толкушка, аксессуар для: погружные блендеры HBAC11PB$q$,$q$4 պարագայի հավաքածու, պաստել երկնագույն, չափաբաժակ, մանրացուցիչ, հարիչ, տրորիչ, պարագա՝ ձեռքի բլենդերներ HBAC11PB-ի համար$q$),
($q$4 accessories set, Red version, Beaker, Chopper, Whisk, Masher Accessory for: Hand Blenders HBAC11RD$q$,$q$Набор из 4 аксессуаров, красный, мерный стакан, измельчитель, венчик, толкушка, аксессуар для: погружные блендеры HBAC11RD$q$,$q$4 պարագայի հավաքածու, կարմիր, չափաբաժակ, մանրացուցիչ, հարիչ, տրորիչ, պարագա՝ ձեռքի բլենդերներ HBAC11RD-ի համար$q$),
($q$4 slice Toaster Black 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, черный, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, սև, 50's Style էսթետիկա$q$),
($q$4 slice Toaster Pastel blue 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, пастельный голубой, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, պաստել երկնագույն, 50's Style էսթետիկա$q$),
($q$4 slice Toaster Pastel green 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, пастельный зеленый, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, պաստել կանաչ, 50's Style էսթետիկա$q$),
($q$4 slice Toaster Pink 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, розовый, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, վարդագույն, 50's Style էսթետիկա$q$),
($q$4 slice Toaster Red 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, красный, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, կարմիր, 50's Style էսթետիկա$q$),
($q$4 slice Toaster Steel 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, сталь, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, պողպատ, 50's Style էսթետիկա$q$),
($q$4 slice Toaster White 50's Style Aesthetic$q$,$q$Тостер на 4 ломтика, белый, эстетика 50's Style$q$,$q$Տոստեր 4 կտորի, սպիտակ, 50's Style էսթետիկա$q$),
($q$Accessories Accessory for: Hoods$q$,$q$Аксессуары, аксессуар для: вытяжки$q$,$q$Պարագաներ, պարագա՝ օդաքաշների համար$q$),
($q$Adaptor Accessory for: Hobs, Hoods$q$,$q$Адаптер, аксессуар для: варочные панели, вытяжки$q$,$q$Ադապտեր, պարագա՝ կերակրասալերի, օդաքաշների համար$q$),
($q$Additional container for ice cream maker accessory SMIC01 Accessory for: Stand Mixer SMIC02$q$,$q$Дополнительный контейнер для мороженицы SMIC01, аксессуар для: планетарный миксер SMIC02$q$,$q$Լրացուցիչ տարա պաղպաղակի սարքի SMIC01 համար, պարագա՝ պլանետար միքսեր SMIC02-ի համար$q$),
($q$Analog and digital Kitchen Scale Black, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, черный, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, սև, փայլուն, 50's Style էսթետիկա$q$),
($q$Analog and digital Kitchen Scale Cream, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, кремовый, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, կրեմագույն, փայլուն, 50's Style էսթետիկա$q$),
($q$Analog and digital Kitchen Scale Pastel blue, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, пастельный голубой, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, պաստել երկնագույն, փայլուն, 50's Style էսթետիկա$q$),
($q$Analog and digital Kitchen Scale Pastel green, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, пастельный зеленый, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, պաստել կանաչ, փայլուն, 50's Style էսթետիկա$q$),
($q$Analog and digital Kitchen Scale Red, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, красный, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, կարմիր, փայլուն, 50's Style էսթետիկա$q$),
($q$Analog and digital Kitchen Scale White, Glossy 50's Style Aesthetic$q$,$q$Аналогово-цифровые кухонные весы, белый, глянцевый, эстетика 50's Style$q$,$q$Անալոգային և թվային խոհանոցային կշեռք, սպիտակ, փայլուն, 50's Style էսթետիկա$q$),
($q$Antifingerprint Accessory for: Ovens$q$,$q$Антиотпечатки, аксессуар для: духовые шкафы$q$,$q$Հակամատնահետք, պարագա՝ ջեռոցների համար$q$),
($q$Anti-Odour filter Accessory for: Hoods$q$,$q$Фильтр против запахов, аксессуар для: вытяжки$q$,$q$Հոտերի դեմ զտիչ, պարագա՝ օդաքաշների համար$q$),
($q$Automatic pop-up Accessory for: Sinks$q$,$q$Автоматический клапан-автомат, аксессуар для: мойки$q$,$q$Ավտոմատ բացվող փական, պարագա՝ լվացարանների համար$q$),
($q$Basket Accessory for: Sinks$q$,$q$Корзина, аксессуар для: мойки$q$,$q$Զամբյուղ, պարագա՝ լվացարանների համար$q$),
($q$Black drip filter coffee machine 50's Style aesthetic$q$,$q$Капельная кофемашина, черный, эстетика 50's Style$q$,$q$Կաթիլային սրճեփ մեքենա, սև, 50's Style էսթետիկա$q$),
($q$Black electric kettle 50's Style aesthetic$q$,$q$Электрический чайник, черный, эстетика 50's Style$q$,$q$Էլեկտրական թեյնիկ, սև, 50's Style էսթետիկա$q$),
($q$Black Glossy refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, черный глянцевый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև փայլուն, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Glossy refrigerator 1720x600x728 mm Free standing 50's Style$q$,$q$Холодильник, черный глянцевый, 1720x600x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև փայլուն, 1720x600x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Glossy refrigerator 1921x796x805 mm Free standing 50's Style$q$,$q$Холодильник, черный глянцевый, 1921x796x805 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև փայլուն, 1921x796x805 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Glossy refrigerator 1968x601x728 mm Free standing 50's Style$q$,$q$Холодильник, черный глянцевый, 1968x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև փայլուն, 1968x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Glossy refrigerator 2050x706x771 mm Free standing 50's Style$q$,$q$Холодильник, черный глянцевый, 2050x706x771 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև փայլուն, 2050x706x771 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Matt refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, черный матовый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, սև մատ, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Black Minibar Refrigerator One Door, Free standing 50's Style$q$,$q$Холодильник-минибар, черный, одна дверь, отдельностоящий, 50's Style$q$,$q$Մինիբար սառնարան, սև, մեկ դուռ, առանձին կանգնող, 50's Style$q$),
($q$Blue Glossy refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, синий глянцевый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կապույտ փայլուն, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Blue Glossy refrigerator 1720x600x728 mm Free standing 50's Style$q$,$q$Холодильник, синий глянцевый, 1720x600x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կապույտ փայլուն, 1720x600x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Blue Glossy refrigerator 1968x601x728 mm Free standing 50's Style$q$,$q$Холодильник, синий глянцевый, 1968x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կապույտ փայլուն, 1968x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Bottle for soda maker SKC01 Accessory for: Water Care SKSB01$q$,$q$Бутылка для сифона SKC01, аксессуар для: Water Care SKSB01$q$,$q$Շիշ գազավորման սարքի SKC01 համար, պարագա՝ Water Care SKSB01-ի համար$q$),
($q$Built-in freezer Single door Universale Aesthetic$q$,$q$Встраиваемый морозильник, одна дверь, эстетика Universale$q$,$q$Ներկառուցվող սառցարան, մեկ դուռ, Universale էսթետիկա$q$),
($q$Built-in freezer Under counter Universale Aesthetic$q$,$q$Встраиваемый морозильник, под столешницу, эстетика Universale$q$,$q$Ներկառուցվող սառցարան, աշխատասեղանի տակ, Universale էսթետիկա$q$),
($q$Built-in refrigerator One Door Universale Aesthetic$q$,$q$Встраиваемый холодильник, одна дверь, эстетика Universale$q$,$q$Ներկառուցվող սառնարան, մեկ դուռ, Universale էսթետիկա$q$),
($q$Built-in refrigerator Top Mount Universale Aesthetic$q$,$q$Встраиваемый холодильник с верхней морозильной камерой, эстетика Universale$q$,$q$Ներկառուցվող սառնարան վերին սառցախցիկով, Universale էսթետիկա$q$),
($q$Built-in washing machine Width: 60 cm, Washing capacity:$q$,$q$Встраиваемая стиральная машина, ширина: 60 см, загрузка:$q$,$q$Ներկառուցվող լվացքի մեքենա, լայնք՝ 60 սմ, լվացման տարողություն՝$q$),
($q$Built-in Wine Cooler Dolce Stil Novo Aesthetic$q$,$q$Встраиваемый винный холодильник, эстетика Dolce Stil Novo$q$,$q$Ներկառուցվող գինու սառնարան, Dolce Stil Novo էսթետիկա$q$),
($q$Bun Warmer Accessory for: Toaster TSBW01$q$,$q$Подставка для подогрева булочек, аксессуар для: тостер TSBW01$q$,$q$Բուլկիների տաքացման հարմարանք, պարագա՝ տոստեր TSBW01-ի համար$q$),
($q$Bun Warmer Accessory for: Toaster TSBW02$q$,$q$Подставка для подогрева булочек, аксессуар для: тостер TSBW02$q$,$q$Բուլկիների տաքացման հարմարանք, պարագա՝ տոստեր TSBW02-ի համար$q$),
($q$Carafe Accessory for: Coffee Machines DCGC01$q$,$q$Графин, аксессуар для: кофемашины DCGC01$q$,$q$Սրվակ, պարագա՝ սրճեփ մեքենաների DCGC01 համար$q$),
($q$Ceiling hood 120 cm Universale Aesthetic$q$,$q$Потолочная вытяжка 120 см, эстетика Universale$q$,$q$Առաստաղի օդաքաշ 120 սմ, Universale էսթետիկա$q$),
($q$Ceiling hood 90 cm Universale Aesthetic$q$,$q$Потолочная вытяжка 90 см, эстетика Universale$q$,$q$Առաստաղի օդաքաշ 90 սմ, Universale էսթետիկա$q$),
($q$Ceramic Filter Accessory for: Hobs$q$,$q$Керамический фильтр, аксессуар для: варочные панели$q$,$q$Կերամիկական զտիչ, պարագա՝ կերակրասալերի համար$q$),
($q$Ceramic Hob 80 cm Universale aesthetic$q$,$q$Керамическая варочная панель 80 см, эстетика Universale$q$,$q$Կերամիկական կերակրասալ 80 սմ, Universale էսթետիկա$q$),
($q$Ceramic Hob 90 cm Universale aesthetic$q$,$q$Керамическая варочная панель 90 см, эстетика Universale$q$,$q$Կերամիկական կերակրասալ 90 սմ, Universale էսթետիկա$q$),
($q$Champagne electric kettle 50's Style aesthetic$q$,$q$Электрический чайник, шампань, эстетика 50's Style$q$,$q$Էլեկտրական թեյնիկ, շամպայն, 50's Style էսթետիկա$q$),
($q$Charcoal filter Accessory for: Hobs$q$,$q$Угольный фильтр, аксессуар для: варочные панели$q$,$q$Ածխածնային զտիչ, պարագա՝ կերակրասալերի համար$q$),
($q$Charcoal filter Accessory for: Hobs, Hoods$q$,$q$Угольный фильтр, аксессуар для: варочные панели, вытяжки$q$,$q$Ածխածնային զտիչ, պարագա՝ կերակրասալերի, օդաքաշների համար$q$),
($q$Charcoal filter Accessory for: Hoods$q$,$q$Угольный фильтр, аксессуар для: вытяжки$q$,$q$Ածխածնային զտիչ, պարագա՝ օդաքաշների համար$q$),
($q$Charcoal filter kit Accessory for: Hoods$q$,$q$Комплект угольных фильтров, аксессуар для: вытяжки$q$,$q$Ածխածնային զտիչների հավաքածու, պարագա՝ օդաքաշների համար$q$),
($q$Child Lock Accessory for: Ovens, Cookers$q$,$q$Защита от детей, аксессуар для: духовые шкафы, плиты$q$,$q$Մանկական պաշտպանություն, պարագա՝ ջեռոցների, սալօջախների համար$q$),
($q$Chimney extension Accessory for: Hoods$q$,$q$Удлинитель дымохода, аксессуар для: вытяжки$q$,$q$Ծխնելույզի երկարացուցիչ, պարագա՝ օդաքաշների համար$q$),
($q$Chimney extension Accessory for: Hoods Universale$q$,$q$Удлинитель дымохода, аксессуар для: вытяжки Universale$q$,$q$Ծխնելույզի երկարացուցիչ, պարագա՝ օդաքաշների Universale համար$q$),
($q$Chimney set Accessory for: Hoods$q$,$q$Комплект дымохода, аксессуар для: вытяжки$q$,$q$Ծխնելույզի հավաքածու, պարագա՝ օդաքաշների համար$q$),
($q$Colander Accessory for: Sinks$q$,$q$Дуршлаг, аксессуар для: мойки$q$,$q$Քամիչ, պարագա՝ լվացարանների համար$q$),
($q$Combi Microwave Built-in Black Dolce Stil Novo aesthetic line$q$,$q$Встраиваемая комбинированная микроволновая печь, черный, линия Dolce Stil Novo$q$,$q$Ներկառուցվող համակցված միկրոալիքային վառարան, սև, Dolce Stil Novo էսթետիկա$q$),
($q$Combi Microwave Countertop Stainless steel Universale aesthetic line$q$,$q$Настольная комбинированная микроволновая печь, нержавеющая сталь, линия Universale$q$,$q$Սեղանի համակցված միկրոալիքային վառարան, չժանգոտվող պողպատ, Universale էսթետիկա$q$),
($q$Combi Microwave Oven 45 cm Selezione aesthetic line$q$,$q$Комбинированная микроволновая печь 45 см, линия Selezione$q$,$q$Համակցված միկրոալիքային վառարան 45 սմ, Selezione էսթետիկա$q$),
($q$Cream electric kettle 50's Style aesthetic$q$,$q$Электрический чайник, кремовый, эстетика 50's Style$q$,$q$Էլեկտրական թեյնիկ, կրեմագույն, 50's Style էսթետիկա$q$)
) AS m(en, ru, hy)
WHERE p.name_en IS NULL AND p.name = m.en;
COMMIT;
