-- Names batch 2.
BEGIN;
UPDATE products p SET name_en = m.en, name = m.ru, name_hy = m.hy
FROM (VALUES
($q$Cream Glossy refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, кремовый глянцевый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կրեմագույն փայլուն, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Cream Glossy refrigerator 1720x600x728 mm Free standing 50's Style$q$,$q$Холодильник, кремовый глянцевый, 1720x600x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կրեմագույն փայլուն, 1720x600x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Cream Glossy refrigerator 1968x601x728 mm Free standing 50's Style$q$,$q$Холодильник, кремовый глянцевый, 1968x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կրեմագույն փայլուն, 1968x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Cream Glossy refrigerator 2050x706x771 mm Free standing 50's Style$q$,$q$Холодильник, кремовый глянцевый, 2050x706x771 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, կրեմագույն փայլուն, 2050x706x771 մմ, առանձին կանգնող, 50's Style$q$),
($q$Cream Minibar Refrigerator One Door, Free standing 50's Style$q$,$q$Холодильник-минибар, кремовый, одна дверь, отдельностоящий, 50's Style$q$,$q$Մինիբար սառնարան, կրեմագույն, մեկ դուռ, առանձին կանգնող, 50's Style$q$),
($q$Decorated / Special Glossy refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, декорированный / специальный глянцевый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, դեկորացված / հատուկ փայլուն, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Decorated / Special Minibar Refrigerator One Door, Free standing 50's Style$q$,$q$Холодильник-минибар, декорированный / специальный, одна дверь, отдельностоящий, 50's Style$q$,$q$Մինիբար սառնարան, դեկորացված / հատուկ, մեկ դուռ, առանձին կանգնող, 50's Style$q$),
($q$Decorative island hood 120 cm Universale Aesthetic$q$,$q$Декоративная островная вытяжка 120 см, эстетика Universale$q$,$q$Դեկորատիվ կղզյակային օդաքաշ 120 սմ, Universale էսթետիկա$q$),
($q$Decorative island hood 90 cm Cortina Aesthetic$q$,$q$Декоративная островная вытяжка 90 см, эстетика Cortina$q$,$q$Դեկորատիվ կղզյակային օդաքաշ 90 սմ, Cortina էսթետիկա$q$),
($q$Decorative island hood 90 cm Universale Aesthetic$q$,$q$Декоративная островная вытяжка 90 см, эстетика Universale$q$,$q$Դեկորատիվ կղզյակային օդաքաշ 90 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 100 cm Classica Aesthetic$q$,$q$Декоративная настенная вытяжка 100 см, эстетика Classica$q$,$q$Դեկորատիվ պատի օդաքաշ 100 սմ, Classica էսթետիկա$q$),
($q$Decorative wall hood 100 cm Victoria Aesthetic$q$,$q$Декоративная настенная вытяжка 100 см, эстетика Victoria$q$,$q$Դեկորատիվ պատի օդաքաշ 100 սմ, Victoria էսթետիկա$q$),
($q$Decorative wall hood 110 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 110 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 110 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 110 cm Victoria Aesthetic$q$,$q$Декоративная настенная вытяжка 110 см, эстетика Victoria$q$,$q$Դեկորատիվ պատի օդաքաշ 110 սմ, Victoria էսթետիկա$q$),
($q$Decorative wall hood 120 cm Classica Aesthetic$q$,$q$Декоративная настенная вытяжка 120 см, эстетика Classica$q$,$q$Դեկորատիվ պատի օդաքաշ 120 սմ, Classica էսթետիկա$q$),
($q$Decorative wall hood 120 cm Portofino Aesthetic$q$,$q$Декоративная настенная вытяжка 120 см, эстетика Portofino$q$,$q$Դեկորատիվ պատի օդաքաշ 120 սմ, Portofino էսթետիկա$q$),
($q$Decorative wall hood 120 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 120 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 120 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 150 cm Classica Aesthetic$q$,$q$Декоративная настенная вытяжка 150 см, эстетика Classica$q$,$q$Դեկորատիվ պատի օդաքաշ 150 սմ, Classica էսթետիկա$q$),
($q$Decorative wall hood 60 cm Coloniale Aesthetic$q$,$q$Декоративная настенная вытяжка 60 см, эстетика Coloniale$q$,$q$Դեկորատիվ պատի օդաքաշ 60 սմ, Coloniale էսթետիկա$q$),
($q$Decorative wall hood 60 cm Cortina Aesthetic$q$,$q$Декоративная настенная вытяжка 60 см, эстетика Cortina$q$,$q$Դեկորատիվ պատի օդաքաշ 60 սմ, Cortina էսթետիկա$q$),
($q$Decorative wall hood 60 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 60 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 60 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 60 cm Victoria Aesthetic$q$,$q$Декоративная настенная вытяжка 60 см, эстетика Victoria$q$,$q$Դեկորատիվ պատի օդաքաշ 60 սմ, Victoria էսթետիկա$q$),
($q$Decorative wall hood 70 cm Classica Aesthetic$q$,$q$Декоративная настенная вытяжка 70 см, эстетика Classica$q$,$q$Դեկորատիվ պատի օդաքաշ 70 սմ, Classica էսթետիկա$q$),
($q$Decorative wall hood 70 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 70 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 70 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 75 cm 50's Style Aesthetic$q$,$q$Декоративная настенная вытяжка 75 см, эстетика 50's Style$q$,$q$Դեկորատիվ պատի օդաքաշ 75 սմ, 50's Style էսթետիկա$q$),
($q$Decorative wall hood 80 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 80 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 80 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 90 cm Classica Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Classica$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Classica էսթետիկա$q$),
($q$Decorative wall hood 90 cm Coloniale Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Coloniale$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Coloniale էսթետիկա$q$),
($q$Decorative wall hood 90 cm Cortina Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Cortina$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Cortina էսթետիկա$q$),
($q$Decorative wall hood 90 cm Dolce Stil Novo Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Dolce Stil Novo$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Dolce Stil Novo էսթետիկա$q$),
($q$Decorative wall hood 90 cm Linea Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Linea$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Linea էսթետիկա$q$),
($q$Decorative wall hood 90 cm Portofino Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Portofino$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Portofino էսթետիկա$q$),
($q$Decorative wall hood 90 cm Universale Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Universale$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Universale էսթետիկա$q$),
($q$Decorative wall hood 90 cm Victoria Aesthetic$q$,$q$Декоративная настенная вытяжка 90 см, эстетика Victoria$q$,$q$Դեկորատիվ պատի օդաքաշ 90 սմ, Victoria էսթետիկա$q$),
($q$Decorative wall hood Divina Cucina, 90 cm Victoria aesthetic$q$,$q$Декоративная настенная вытяжка Divina Cucina, 90 см, эстетика Victoria$q$,$q$Դեկորատիվ պատի օդաքաշ Divina Cucina, 90 սմ, Victoria էսթետիկա$q$),
($q$Digital Kitchen Scale Black, Matt Collezione Aesthetic$q$,$q$Цифровые кухонные весы, черный, матовый, эстетика Collezione$q$,$q$Թվային խոհանոցային կշեռք, սև, մատ, Collezione էսթետիկա$q$),
($q$Digital Kitchen Scale Emerald Green, Matt Collezione Aesthetic$q$,$q$Цифровые кухонные весы, изумрудно-зеленый, матовый, эстетика Collezione$q$,$q$Թվային խոհանոցային կշեռք, զմրուխտ կանաչ, մատ, Collezione էսթետիկա$q$),
($q$Digital Kitchen Scale Storm Blue, Matt Collezione Aesthetic$q$,$q$Цифровые кухонные весы, грозовой синий, матовый, эстетика Collezione$q$,$q$Թվային խոհանոցային կշեռք, փոթորկային կապույտ, մատ, Collezione էսթետիկա$q$),
($q$Digital Kitchen Scale White, Matt Collezione Aesthetic$q$,$q$Цифровые кухонные весы, белый, матовый, эстетика Collezione$q$,$q$Թվային խոհանոցային կշեռք, սպիտակ, մատ, Collezione էսթետիկա$q$),
($q$Double lever filtered water kitchen tap 50's Style Aesthetic$q$,$q$Кухонный смеситель с двумя рычагами и фильтрованной водой, эстетика 50's Style$q$,$q$Երկու լծակով խոհանոցային ծորակ զտված ջրով, 50's Style էսթետիկա$q$),
($q$Double lever filtered water kitchen tap Coloniale Aesthetic$q$,$q$Кухонный смеситель с двумя рычагами и фильтрованной водой, эстетика Coloniale$q$,$q$Երկու լծակով խոհանոցային ծորակ զտված ջրով, Coloniale էսթետիկա$q$),
($q$Double lever filtered water kitchen tap Universale Aesthetic$q$,$q$Кухонный смеситель с двумя рычагами и фильтрованной водой, эстетика Universale$q$,$q$Երկու լծակով խոհանոցային ծորակ զտված ջրով, Universale էսթետիկա$q$),
($q$Double lever kitchen tap Coloniale Aesthetic$q$,$q$Кухонный смеситель с двумя рычагами, эстетика Coloniale$q$,$q$Երկու լծակով խոհանոցային ծորակ, Coloniale էսթետիկա$q$),
($q$DownDraft 12 cm Universale Aesthetic$q$,$q$Выдвижная вытяжка DownDraft 12 см, эстетика Universale$q$,$q$DownDraft դուրսբացվող օդաքաշ 12 սմ, Universale էսթետիկա$q$),
($q$DownDraft 60 cm Universale Aesthetic$q$,$q$Выдвижная вытяжка DownDraft 60 см, эстетика Universale$q$,$q$DownDraft դուրսբացվող օդաքաշ 60 սմ, Universale էսթետիկա$q$),
($q$Electric Kettle Sicily is my love collection Smeg & Dolce&Gabbana$q$,$q$Электрический чайник, коллекция Sicily is my love, Smeg & Dolce&Gabbana$q$,$q$Էլեկտրական թեյնիկ, Sicily is my love հավաքածու, Smeg & Dolce&Gabbana$q$),
($q$Electric plates Hob 30 cm Classica aesthetic$q$,$q$Варочная панель с электрическими конфорками 30 см, эстетика Classica$q$,$q$Էլեկտրական սկավառակներով կերակրասալ 30 սմ, Classica էսթետիկա$q$),
($q$Emerald Green electric kettle 50's Style aesthetic$q$,$q$Электрический чайник, изумрудно-зеленый, эстетика 50's Style$q$,$q$Էլեկտրական թեյնիկ, զմրուխտ կանաչ, 50's Style էսթետիկա$q$),
($q$Emerald Green Matt refrigerator 1530x601x728 mm Free standing 50's Style$q$,$q$Холодильник, изумрудно-зеленый матовый, 1530x601x728 мм, отдельностоящий, 50's Style$q$,$q$Սառնարան, զմրուխտ կանաչ մատ, 1530x601x728 մմ, առանձին կանգնող, 50's Style$q$),
($q$Espresso coffee machine with milk frother Black 50's Style aesthetic$q$,$q$Эспрессо-кофемашина с капучинатором, черный, эстетика 50's Style$q$,$q$Էսպրեսո սրճեփ մեքենա կաթի փրփրացուցիչով, սև, 50's Style էսթետիկա$q$),
($q$Exhaust kit Accessory for: Hobs$q$,$q$Комплект для отвода воздуха, аксессуар для: варочные панели$q$,$q$Օդահեռացման հավաքածու, պարագա՝ կերակրասալերի համար$q$),
($q$Extension kit Accessory for: Dishwashers$q$,$q$Удлинительный комплект, аксессуар для: посудомоечные машины$q$,$q$Երկարացման հավաքածու, պարագա՝ ամանլվացքի մեքենաների համար$q$),
($q$Fan assisted Oven 60 cm Classica aesthetic line$q$,$q$Духовой шкаф с конвекцией 60 см, линия Classica$q$,$q$Կոնվեկցիայով ջեռոց 60 սմ, Classica էսթետիկա$q$),
($q$Fan assisted Oven 60 cm Coloniale aesthetic line$q$,$q$Духовой шкаф с конвекцией 60 см, линия Coloniale$q$,$q$Կոնվեկցիայով ջեռոց 60 սմ, Coloniale էսթետիկա$q$),
($q$Fan assisted Oven 60 cm Linea aesthetic line$q$,$q$Духовой шкаф с конвекцией 60 см, линия Linea$q$,$q$Կոնվեկցիայով ջեռոց 60 սմ, Linea էսթետիկա$q$),
($q$Feet Kit Accessory for: Cookers$q$,$q$Комплект ножек, аксессуар для: плиты$q$,$q$Ոտքերի հավաքածու, պարագա՝ սալօջախների համար$q$),
($q$Filter grid Accessory for: Hoods$q$,$q$Решётка фильтра, аксессуар для: вытяжки$q$,$q$Զտիչի վանդակ, պարագա՝ օդաքաշների համար$q$),
($q$Food Processor Accessory for: Hand Blenders HBFP11$q$,$q$Кухонный комбайн, аксессуар для: погружные блендеры HBFP11$q$,$q$Խոհանոցային կոմբայն, պարագա՝ ձեռքի բլենդերներ HBFP11-ի համար$q$),
($q$Franges Accessory for: Hoods$q$,$q$Накладка, аксессуар для: вытяжки$q$,$q$Եզրաշերտ, պարագա՝ օդաքաշների համար$q$),
($q$Free standing Classica Aesthetic$q$,$q$Отдельностоящий, эстетика Classica$q$,$q$Առանձին կանգնող, Classica էսթետիկա$q$),
($q$Free-standing dishwasher 60 cm width 50's Style Aesthetic$q$,$q$Отдельностоящая посудомоечная машина шириной 60 см, эстетика 50's Style$q$,$q$Առանձին կանգնող ամանլվացքի մեքենա, 60 սմ լայնք, 50's Style էսթետիկա$q$),
($q$Free-standing dishwasher 60 cm width Classica Aesthetic$q$,$q$Отдельностоящая посудомоечная машина шириной 60 см, эстетика Classica$q$,$q$Առանձին կանգնող ամանլվացքի մեքենա, 60 սմ լայնք, Classica էսթետիկա$q$),
($q$Free-standing dishwasher 60 cm width Universale Aesthetic$q$,$q$Отдельностоящая посудомоечная машина шириной 60 см, эстетика Universale$q$,$q$Առանձին կանգնող ամանլվացքի մեքենա, 60 սմ լայնք, Universale էսթետիկա$q$),
($q$Free Standing freezer Single door Universale Aesthetic$q$,$q$Отдельностоящий морозильник, одна дверь, эстетика Universale$q$,$q$Առանձին կանգնող սառցարան, մեկ դուռ, Universale էսթետիկա$q$),
($q$Free Standing freezer Under counter Universale Aesthetic$q$,$q$Отдельностоящий морозильник, под столешницу, эстетика Universale$q$,$q$Առանձին կանգնող սառցարան, աշխատասեղանի տակ, Universale էսթետիկա$q$),
($q$Free standing refrigerator 2 Doors & 2 Drawers Universale Aesthetic$q$,$q$Отдельностоящий холодильник, 2 двери и 2 ящика, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան, 2 դուռ և 2 դարակ, Universale էսթետիկա$q$),
($q$Free standing refrigerator 4 Doors Coloniale Aesthetic$q$,$q$Отдельностоящий холодильник, 4 двери, эстетика Coloniale$q$,$q$Առանձին կանգնող սառնարան, 4 դուռ, Coloniale էսթետիկա$q$),
($q$Free standing refrigerator 4 Doors Universale Aesthetic$q$,$q$Отдельностоящий холодильник, 4 двери, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան, 4 դուռ, Universale էսթետիկա$q$),
($q$Free standing refrigerator 4 Doors Victoria Aesthetic$q$,$q$Отдельностоящий холодильник, 4 двери, эстетика Victoria$q$,$q$Առանձին կանգնող սառնարան, 4 դուռ, Victoria էսթետիկա$q$),
($q$Free standing refrigerator Bottom Mount Aesthetic$q$,$q$Отдельностоящий холодильник с нижней морозильной камерой$q$,$q$Առանձին կանգնող սառնարան ստորին սառցախցիկով$q$),
($q$Free standing refrigerator Bottom Mount Classica Aesthetic$q$,$q$Отдельностоящий холодильник с нижней морозильной камерой, эстетика Classica$q$,$q$Առանձին կանգնող սառնարան ստորին սառցախցիկով, Classica էսթետիկա$q$),
($q$Free standing refrigerator Bottom Mount Coloniale Aesthetic$q$,$q$Отдельностоящий холодильник с нижней морозильной камерой, эстетика Coloniale$q$,$q$Առանձին կանգնող սառնարան ստորին սառցախցիկով, Coloniale էսթետիկա$q$),
($q$Free standing refrigerator Bottom Mount Universale Aesthetic$q$,$q$Отдельностоящий холодильник с нижней морозильной камерой, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան ստորին սառցախցիկով, Universale էսթետիկա$q$),
($q$Free standing refrigerator One Door Universale Aesthetic$q$,$q$Отдельностоящий холодильник, одна дверь, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան, մեկ դուռ, Universale էսթետիկա$q$),
($q$Free standing refrigerator Smeg & Dolce&Gabbana 50's Style Aesthetic$q$,$q$Отдельностоящий холодильник Smeg & Dolce&Gabbana, эстетика 50's Style$q$,$q$Առանձին կանգնող սառնարան Smeg & Dolce&Gabbana, 50's Style էսթետիկա$q$),
($q$Free standing refrigerator Top Mount Universale Aesthetic$q$,$q$Отдельностоящий холодильник с верхней морозильной камерой, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան վերին սառցախցիկով, Universale էսթետիկա$q$),
($q$Free standing refrigerator Under counter Universale Aesthetic$q$,$q$Отдельностоящий холодильник, под столешницу, эстетика Universale$q$,$q$Առանձին կանգնող սառնարան, աշխատասեղանի տակ, Universale էսթետիկա$q$),
($q$Free-standing washing machine Width: 60 cm, Washing capacity:$q$,$q$Отдельностоящая стиральная машина, ширина: 60 см, загрузка:$q$,$q$Առանձին կանգնող լվացքի մեքենա, լայնք՝ 60 սմ, լվացման տարողություն՝$q$),
($q$Free-standing washing machine Width: 60 cm, Washing capacity: 10 kg$q$,$q$Отдельностоящая стиральная машина, ширина: 60 см, загрузка: 10 кг$q$,$q$Առանձին կանգնող լվացքի մեքենա, լայնք՝ 60 սմ, լվացման տարողություն՝ 10 կգ$q$),
($q$Free-standing washing machine Width: 60 cm, Washing capacity: 8 kg$q$,$q$Отдельностоящая стиральная машина, ширина: 60 см, загрузка: 8 кг$q$,$q$Առանձին կանգնող լվացքի մեքենա, լայնք՝ 60 սմ, լվացման տարողություն՝ 8 կգ$q$),
($q$Fridge FAB28 | 917 Salzburg Porsche x SMEG Limited Edition$q$,$q$Холодильник FAB28 | 917 Salzburg Porsche x SMEG Limited Edition$q$,$q$Սառնարան FAB28 | 917 Salzburg Porsche x SMEG Limited Edition$q$),
($q$Fridge FAB28 | Carrara White Porsche x SMEG$q$,$q$Холодильник FAB28 | Carrara White Porsche x SMEG$q$,$q$Սառնարան FAB28 | Carrara White Porsche x SMEG$q$),
($q$Fridge FAB28 | Shade Green Porsche x SMEG$q$,$q$Холодильник FAB28 | Shade Green Porsche x SMEG$q$,$q$Սառնարան FAB28 | Shade Green Porsche x SMEG$q$),
($q$Fully-integrated built-in dishwasher 45 cm width Universale Aesthetic$q$,$q$Полностью встраиваемая посудомоечная машина шириной 45 см, эстетика Universale$q$,$q$Ամբողջությամբ ներկառուցվող ամանլվացքի մեքենա, 45 սմ լայնք, Universale էսթետիկա$q$),
($q$Fully-integrated built-in dishwasher 60 cm width Universale Aesthetic$q$,$q$Полностью встраиваемая посудомоечная машина шириной 60 см, эстетика Universale$q$,$q$Ամբողջությամբ ներկառուցվող ամանլվացքի մեքենա, 60 սմ լայնք, Universale էսթետիկա$q$),
($q$Fully integrated built-in washing machine Width: 60 cm, Washing capacity: 7 kg$q$,$q$Полностью встраиваемая стиральная машина, ширина: 60 см, загрузка: 7 кг$q$,$q$Ամբողջությամբ ներկառուցվող լվացքի մեքենա, լայնք՝ 60 սմ, լվացման տարողություն՝ 7 կգ$q$)
) AS m(en, ru, hy)
WHERE p.name_en IS NULL AND p.name = m.en;
COMMIT;
