
UPDATE public.collections SET name_en='FAB · 50''s Style', name_hy='FAB · 50-ականների ոճ', description='Культовые ретро-холодильники с ручной отделкой изгибов.', description_en='Iconic retro fridges with hand-finished curves.', description_hy='Ձեռքով հղկված կորերով դասական ռետրո սառնարաններ։' WHERE slug='fab-50s';
UPDATE public.collections SET name_en='Sicily Is My Love', name_hy='Sicily Is My Love', description='Smeg × Dolce&Gabbana — расписанные вручную силуэты Сицилии.', description_en='Smeg × Dolce&Gabbana — hand-painted silhouettes of Sicily.', description_hy='Smeg × Dolce&Gabbana — ձեռքով նկարված Սիցիլիայի ուրվագծեր։' WHERE slug='dolce-gabbana-sicily';
UPDATE public.collections SET name_en='Coca-Cola', name_hy='Coca-Cola', description='Лимитированная коллекция в иконическом красном цвете.', description_en='Limited edition in the iconic red colour.', description_hy='Սահմանափակ հավաքածու դասական կարմիր գույնով։' WHERE slug='coca-cola';
UPDATE public.collections SET name_en='Smeg × Dolce & Gabbana', name_hy='Smeg × Dolce & Gabbana', description='Сицилийская роспись вручную на премиальной технике.', description_en='Hand-painted Sicilian art on premium appliances.', description_hy='Ձեռքով նկարված սիցիլիական արվեստ պրեմիում տեխնիկայի վրա։' WHERE slug='dolce-gabbana';
UPDATE public.collections SET name_en='Smeg500', name_hy='Smeg500', description='Холодильник из настоящего капота Fiat 500.', description_en='A fridge made from a real Fiat 500 bonnet.', description_hy='Սառնարան՝ պատրաստված իրական Fiat 500-ի կափարիչից։' WHERE slug='smeg500';
UPDATE public.collections SET name_en='Porsche x Smeg', name_hy='Porsche x Smeg', description='Капсульная коллекция в стиле гоночного дизайна Porsche.', description_en='Capsule collection inspired by Porsche racing design.', description_hy='Կապսուլային հավաքածու՝ ներշնչված Porsche-ի մրցարշավային ձևավորմամբ։' WHERE slug='porsche';
UPDATE public.collections SET name_en='Portofino', name_hy='Portofino', description='Элегантность Ривьеры и профессиональное мастерство.', description_en='Riviera elegance, professional craftsmanship.', description_hy='Ռիվիերայի նրբագեղություն և պրոֆեսիոնալ վարպետություն։' WHERE slug='portofino';
UPDATE public.collections SET name_en='Linea', name_hy='Linea', description='Архитектурный минимализм для современных кухонь.', description_en='Architectural minimalism for modern kitchens.', description_hy='Ճարտարապետական մինիմալիզմ ժամանակակից խոհանոցների համար։' WHERE slug='linea';
UPDATE public.collections SET name_en='Victoria', name_hy='Victoria', description='Деревенский шарм, переосмысленный с итальянской точностью.', description_en='Country charm, reinvented with Italian precision.', description_hy='Գյուղական հմայք՝ վերաիմաստավորված իտալական ճշգրտությամբ։' WHERE slug='victoria';
UPDATE public.collections SET name_en='Coloniale', name_hy='Coloniale', description='Вечная традиция в прочных материалах.', description_en='Timeless tradition in solid materials.', description_hy='Հավերժական ավանդույթ՝ ամուր նյութերում։' WHERE slug='coloniale';
UPDATE public.collections SET name_en='Dolce Stil Novo', name_hy='Dolce Stil Novo', description='Чистые профессиональные линии с медными деталями.', description_en='Pure professional lines with copper details.', description_hy='Մաքուր պրոֆեսիոնալ գծեր՝ պղնձե դետալներով։' WHERE slug='dolce-stil-novo';
UPDATE public.collections SET name_en='Classica', name_hy='Classica', description='Сдержанная классика для встраиваемых кухонь.', description_en='Restrained classics for built-in kitchens.', description_hy='Զուսպ դասականություն ներկառուցվող խոհանոցների համար։' WHERE slug='classica';
